MIGENG-358: Numa Pinnings Flag rule and tests
project-xavier/xavier-analytics pull request #48
Opened 2020-02-19 15:51 UTC by m-brophy

https://issues.redhat.com/browse/WINDUPRULE-358

This PR requires work in xavier-integration to work end-to-end

2020-03-17 12:40 UTC, carlosthe19916 reviewed
@m-brophy The code and the tests look good to me.

2020-03-17 13:45 UTC, mrizzi submitted a review, later dismissed
thanks @m-brophy for this new rule :+1:

2020-03-17 14:13 UTC, mrizzi requested changes
@m-brophy there has been a change in requirement https://issues.redhat.com/browse/MIGENG-358?focusedCommentId=14000961&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14000961 and hence this PR has to change consistently.

2020-03-17 14:13 UTC, mrizzi commented on src/main/java/org/jboss/xavier/analytics/functions/HelperFunctions.java
> +        NUMA_PINNINGS(WorkloadInventoryReportModel.NUMA_PINNINGS_FLAG_NAME, false);
Following https://issues.redhat.com/browse/MIGENG-358?focusedCommentId=14000961&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14000961, please change this to become `CPU_AFFINITY`

2020-03-17 18:22 UTC, mperezco commented
Could we please change the name of this flag to "CPU affinity"

2020-03-18 11:21 UTC, carlosthe19916 commented
@m-brophy Thanks for all the changes... I've tested your last changes in CI and it worked fine. I've also reported a couple of screenshots from the test in this comment: https://github.com/project-xavier/xavier-integration/pull/84#pullrequestreview-376762526

2020-03-18 11:22 UTC, carlosthe19916 approved these changes

2020-03-18 11:23 UTC, merged